In [3]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB

In [4]:
df = pd.read_csv("C:/Users/user/Downloads/datascience/Python/iris.csv")
df.head(2)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [6]:
df["is_setosa"] = (df["Species"] == "setosa") * 1
df.head(2)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species  is_setosa
0           5.1          3.5           1.4          0.2  setosa          1
1           4.9          3.0           1.4          0.2  setosa          1

In [9]:
df["is_setosa"].value_counts(normalize = True)

is_setosa
0    0.666667
1    0.333333
Name: proportion, dtype: float64

In [12]:
model = GaussianNB().fit(X = df.iloc[:,:4], y = df["is_setosa"])

In [13]:
model.class_prior_

array([0.66666667, 0.33333333])

In [20]:
model.theta_

array([[6.262, 2.872, 4.906, 1.676],
       [5.006, 3.428, 1.462, 0.246]])

In [27]:
pred = model.predict_proba(df.iloc[:,:4])
pred = pred[:,1]
pred[:4]

array([1., 1., 1., 1.])

In [28]:
from sklearn.metrics import accuracy_score

In [29]:
pred_class = (pred > 0.5) + 0

In [30]:
accuracy_score(y_true = df["is_setosa"], y_pred = pred_class)

1.0

#1 BMI가 0 초과인 데이터만 사용하여 나이브 베이즈 분류를 실시하고자 한다. outcome을 종속변수로 하고 나머지 변수를 독립변수로 할 때 종속변수의 사전확률은?
*diabetes.csv 파일 사용
*Outcome 1을 대상으로 사전확를을 계산한다.

In [37]:
df = pd.read_csv("C:/Users/user/Downloads/datascience/Python/diabetes.csv")
df.head(2)
df_sub = df.loc[df["BMI"] > 0, :]
print(df_sub["Outcome"].value_counts(normalize = True))
print(df_sub.columns)

Outcome
0    0.648613
1    0.351387
Name: proportion, dtype: float64
Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')


In [39]:
model = GaussianNB().fit(X = df_sub.iloc[:, :-1], y = df_sub["Outcome"])

In [40]:
model.class_prior_

array([0.64861295, 0.35138705])

#2 혈압, 혈당, 나이를 독립변수로 하고 당뇨 발병 여부를 종속변수로 했을 때 그 정확도는 얼마인가?
*diabates.csv파일 사용
*Outcome 1을 대상으로 사전확률을 계산한다.

In [58]:
model = GaussianNB().fit(X = df[["BloodPressure", "Age", "Glucose"]], y = df["Outcome"])
pred = model.predict_proba(df[["BloodPressure", "Age", "Glucose"]])[:,1]
pred_class = (pred > 0.5) + 0
accuracy_score(y_true = df["Outcome"], y_pred = pred_class)

0.7552083333333334

#3 임신여부, 연령대, BMI, 혈당을 독립변수로 하고 당뇨 발병 여부를 종속변수로 했을때 나이브 베이즈와 로지스틱 회귀 분석을 실시하고 둘 중 정확도가 높은 모델의 정확도는?
*diabetes.csv파일 사용
*BMI 가 0 초과인 것을 사용하며 학습/평가 데이터 세트를 8:2로 분할, seed 는 123
*연령대는 Age가 21인 경우 20으로, 29인 경우 30으로 계산한다.
*sklearn의 로지스틱 회귀함수를 사용하며, 임계값(threshold)는 0.5로 한다.

In [104]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [109]:
df = pd.read_csv("C:/Users/user/Downloads/datascience/Python/diabetes.csv")
df["age"] =(df["Age"] // 10) * 10
df["is_preg"] =(df["Pregnancies"] > 0) + 0
df_sub = df.loc[df["BMI"] > 0, :]
df_train, df_test = train_test_split(df_sub, train_size = 0.8, random_state = 123)

In [110]:
X1 = df_train[["is_preg", "age", "BMI", "Glucose"]] 
y1 = df_train["Outcome"]
model1 = LogisticRegression().fit(X = X1, y = y1)
pred1 = model1.predict_proba(df_test[["is_preg", "age", "BMI", "Glucose"]])[:,1]
pred1_class = (pred1 > 0.5) + 0

In [111]:
model2 = GaussianNB().fit(X = X1, y = y1)
pred2 = model2.predict_proba(df_test[["is_preg", "age", "BMI", "Glucose"]])[:,1]
pred2_class = (pred2 > 0.5) + 0

In [112]:
acc1 = accuracy_score(y_true = df_test["Outcome"], y_pred = pred1_class)
acc2 = accuracy_score(y_true = df_test["Outcome"], y_pred = pred2_class)
print(acc1)
print(acc2)

0.8289473684210527
0.8026315789473685
