In [48]:
import numpy as np
import pandas as pd
from statsmodels.formula.api import ols

In [49]:
df = pd.read_csv("C:/Users/user/Downloads/datascience/Python/iris.csv")
df.head(2)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [50]:
#model = ols(formula = "Sepal.Length ~ Sepal.Width", data=df).fit()
#model

In [51]:
df.columns = ["SL", "SW", "PL", "PW", "Species"]
df.columns

Index(['SL', 'SW', 'PL', 'PW', 'Species'], dtype='object')

In [52]:
model = ols(formula = "SL ~ SW", data = df).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                     SL   R-squared:                       0.014
Model:                            OLS   Adj. R-squared:                  0.007
Method:                 Least Squares   F-statistic:                     2.074
Date:                Mon, 22 Jul 2024   Prob (F-statistic):              0.152
Time:                        12:13:56   Log-Likelihood:                -183.00
No. Observations:                 150   AIC:                             370.0
Df Residuals:                     148   BIC:                             376.0
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      6.5262      0.479     13.628      0.000       5.580       7.473
SW            -0.2234      0.155     -1.440      0.152      -0.530       0.083
==============================================================================
Omnibus:                        4.389   Durbin-Watson:                   0.952
Prob(Omnibus):                  0.111   Jarque-Bera (JB):                4.237
Skew:                           0.360   Prob(JB):                        0.120
Kurtosis:                       2.600   Cond. No.                         24.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [53]:
model = ols(formula = "PL ~ PW", data = df).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                     PL   R-squared:                       0.927
Model:                            OLS   Adj. R-squared:                  0.927
Method:                 Least Squares   F-statistic:                     1882.
Date:                Mon, 22 Jul 2024   Prob (F-statistic):           4.68e-86
Time:                        12:13:56   Log-Likelihood:                -101.18
No. Observations:                 150   AIC:                             206.4
Df Residuals:                     148   BIC:                             212.4
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      1.0836      0.073     14.850      0.000       0.939       1.228
PW             2.2299      0.051     43.387      0.000       2.128       2.332
==============================================================================
Omnibus:                        2.438   Durbin-Watson:                   1.430
Prob(Omnibus):                  0.295   Jarque-Bera (JB):                1.966
Skew:                           0.211   Prob(JB):                        0.374
Kurtosis:                       3.369   Cond. No.                         3.70
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

y = 2.2299x + 1.0836

In [54]:
model.predict(df.iloc[:6, ])

0    1.529546
1    1.529546
2    1.529546
3    1.529546
4    1.529546
5    1.975534
dtype: float64

In [55]:
df["pred"] = model.predict(df)
df

SL   SW   PL   PW    Species      pred
0    5.1  3.5  1.4  0.2     setosa  1.529546
1    4.9  3.0  1.4  0.2     setosa  1.529546
2    4.7  3.2  1.3  0.2     setosa  1.529546
3    4.6  3.1  1.5  0.2     setosa  1.529546
4    5.0  3.6  1.4  0.2     setosa  1.529546
..   ...  ...  ...  ...        ...       ...
145  6.7  3.0  5.2  2.3  virginica  6.212421
146  6.3  2.5  5.0  1.9  virginica  5.320445
147  6.5  3.0  5.2  2.0  virginica  5.543439
148  6.2  3.4  5.4  2.3  virginica  6.212421
149  5.9  3.0  5.1  1.8  virginica  5.097451

[150 rows x 6 columns]

In [56]:
from sklearn.linear_model import LinearRegression

In [57]:
#model = LinearRegression().fit(X = df["PL"],
#                               y= df["PW"])

In [58]:
df[["PL"]].head()

PL
0  1.4
1  1.4
2  1.3
3  1.5
4  1.4

In [59]:
df.iloc[[0], ]

SL   SW   PL   PW Species      pred
0  5.1  3.5  1.4  0.2  setosa  1.529546

In [60]:
model = LinearRegression().fit(X = df[["PL"]],
                               y= df[["PW"]])
model

LinearRegression()

In [61]:
model.coef_

array([[0.41575542]])

In [62]:
model.intercept_

array([-0.36307552])

In [63]:
model.predict(df[["PL"]])

array([[0.21898206],
       [0.21898206],
       [0.17740652],
       [0.2605576 ],
       [0.21898206],
       [0.34370869],
       [0.21898206],
       [0.2605576 ],
       [0.21898206],
       [0.2605576 ],
       [0.2605576 ],
       [0.30213314],
       [0.21898206],
       [0.09425544],
       [0.13583098],
       [0.2605576 ],
       [0.17740652],
       [0.21898206],
       [0.34370869],
       [0.2605576 ],
       [0.34370869],
       [0.2605576 ],
       [0.0526799 ],
       [0.34370869],
       [0.42685977],
       [0.30213314],
       [0.30213314],
       [0.2605576 ],
       [0.21898206],
       [0.30213314],
       [0.30213314],
       [0.2605576 ],
       [0.2605576 ],
       [0.21898206],
       [0.2605576 ],
       [0.13583098],
       [0.17740652],
       [0.21898206],
       [0.17740652],
       [0.2605576 ],
       [0.17740652],
       [0.17740652],
       [0.17740652],
       [0.30213314],
       [0.42685977],
       [0.21898206],
       [0.30213314],
       [0.218

In [64]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [65]:
mean_absolute_error(y_true = df["PL"], y_pred = df["PW"])

2.558666666666667

In [66]:
mean_squared_error(y_true = df["PL"], y_pred = df["PW"])

7.645466666666667

In [67]:
mean_squared_error(y_true = df["PL"], y_pred = df["PW"]) ** 0.5

2.76504370067937

#1 종속변수를 registered, 독립변수를 temp로 했을 때 결정계수는?
*bike.csv 사용
*statsmodels 함수 활용
*학습 데이터 비율을 70%, seed를 123으로 설정 

In [90]:
from sklearn.model_selection import train_test_split

In [91]:
df = pd.read_csv("C:/Users/user/Downloads/datascience/Python/bike.csv")
df.head(2)

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40

In [94]:
train_set, test_set = train_test_split(df, train_size = 0.7, random_state = 123)
train_set.head(2)

datetime  season  holiday  workingday  weather   temp  \
4046  2011-09-19 15:00:00       3        0           1        2  24.60   
9262  2012-09-09 07:00:00       3        0           0        1  22.14   

       atemp  humidity  windspeed  casual  registered  count  
4046  30.305        60    15.0013      44         143    187  
9262  25.760        73    11.0014      20          50     70

In [96]:
model = ols(formula = "registered ~ temp", data= train_set).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:             registered   R-squared:                       0.106
Model:                            OLS   Adj. R-squared:                  0.106
Method:                 Least Squares   F-statistic:                     902.3
Date:                Mon, 22 Jul 2024   Prob (F-statistic):          1.92e-187
Time:                        12:21:20   Log-Likelihood:                -48650.
No. Observations:                7620   AIC:                         9.730e+04
Df Residuals:                    7618   BIC:                         9.732e+04
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     27.5151      4.559      6.036      0.000      18.579      36.452
temp           6.3391      0.211     30.038      0.000       5.925       6.753
==============================================================================
Omnibus:                     2097.525   Durbin-Watson:                   2.022
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5337.402
Skew:                           1.502   Prob(JB):                         0.00
Kurtosis:                       5.790   Cond. No.                         60.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

#2 종속변수를 casual, 독립변수를 atemp로 했을 때 RMSE는?
*bike.csv 사용
*statsmodels 함수 사용
*학습 데이터 비율을 70%, seed를 123으로 설정

In [122]:
model = ols(formula = "casual ~ atemp", data = train_set).fit()
pred = model.predict(test_set)

In [125]:
(sum((test_set["casual"] - pred)**2) / (test_set.shape[0]-2)) ** 0.5

44.4759900663061

In [127]:
mean_squared_error(y_true = test_set["casual"], y_pred = pred) ** 0.5

44.46237010271433

#3 종속변수를 casual, 독립변수를 atemp로 했을 때 여름과 겨울의 RMSE차이는?
*bike.csv 파일 사용
*statsmodel 함수 활용
*학습 데이터 비율을 70%, seed를 123으로 설정
*RMSE의 차이는 절대값을 취한다.

In [144]:
df_sum = df.loc[df["season"] == 2, :]
df_win = df.loc[df["season"] == 4, :] 
train_set1, test_set1 = train_test_split(df_sum, train_size = 0.7, random_state = 123)
train_set2, test_set2 = train_test_split(df_win, train_size = 0.7, random_state = 123)

In [147]:
model1 = ols(formula = "casual ~ atemp", data = train_set1).fit()
model2 = ols(formula = "casual ~ atemp", data = train_set2).fit()
pred1 = model1.predict(test_set1)
pred2 = model2.predict(test_set2)

In [148]:
rmse_sum = (sum((test_set1["casual"] - pred1) **2) / (test_set1.shape[0]-2)) ** 0.5

In [149]:
rmse_win = (sum((test_set2["casual"] - pred2) **2) / (test_set2.shape[0]-2)) ** 0.5

In [151]:
abs(rmse_sum - rmse_win)

8.65905098754019

In [155]:
abs((mean_squared_error(y_true = test_set1["casual"], y_pred = pred1))**0.5 - (mean_squared_error(y_true = test_set2["casual"], y_pred = pred2))**0.5)

8.648423450414157